language: node_js
node_js:
- '0.10'
deploy:
  provider: s3
  access_key_id:
    secure: oNsRAlEEyMR5B5mOUM5TkJfmTglTn+M7hooexGgQPiEuRhcIk2dOP7t0ijDNrUHOOwhtPPYENYitOSPDFhwZna1RePZiyGRH9PBAbRUBu/ViBC+xZ06TnWTHkNJygKrL1NQpqSiMg1c9bg8zcMMkg7MPYIKEWhyguC7Zh7WW3aY=
  secret_access_key:
    secure: ieOBf0VlvtePQCtModrcnRO6XTL6zTZPUYEpPRo/8dLwXROEhvoTB2zAMz62nk/GVdrNnrtqqqKczSNiQxxEh4sYhvSqV4tdRu2y/WtOprFUh8GbHxlF73vdcP3U/IByqNeSsvqngj3h0VZiHNXF1rtSnFJhgakhu+0LgKO3hCQ=
  bucket: oyam.ca
  endpoint: oyam.ca.s3-website-us-east-1.amazonaws.com
  region: us-east-1
  skip_cleanup: true
  local-dir: deploy
  acl: public_read
  on:
    repo: mayo/oyam.ca
    branch: master
